### ISSUE TITLE
[v.1.9.0] Message Rotation stops after a while

### ISSUE THREAD

**Issue by carca55gr1nd3r** [SpunkyBot/spunkybot#50]
Not sure if it just me but by use of v.1.9.0 the rotation message stops after a some days.

some settings I use:
- change the parameter rules_frequency to 30
- add some to the commentar at settings.conf to this parameter: 
; Interval in seconds between each rule / rotation message Default: 90
 
The behaviour can be fixed by restart of the bot

last lines at the console:

 ```
 File "/home/urt/spunkybot-1.9.0/lib/pyquake3.py", line 188, in rcon_update
    data = self.rcon('status')[1]
  File "/home/urt/spunkybot-1.9.0/lib/pyquake3.py", line 126, in rcon
    r_cmd = self.command('rcon "%s" %s' % (self.rcon_password, cmd))
  File "/home/urt/spunkybot-1.9.0/lib/pyquake3.py", line 120, in command
    raise Exception('Server response timed out')
Exception: Server response timed out
[06.07.2017 16:42:52] ERROR    Server response timed out
Traceback (most recent call last):
  File "spunky.py", line 3419, in rcon_process
    self.quake.rcon_update()
  File "/home/urt/spunkybot-1.9.0/lib/pyquake3.py", line 188, in rcon_update
    data = self.rcon('status')[1]
  File "/home/urt/spunkybot-1.9.0/lib/pyquake3.py", line 126, in rcon
    r_cmd = self.command('rcon "%s" %s' % (self.rcon_password, cmd))
  File "/home/urt/spunkybot-1.9.0/lib/pyquake3.py", line 120, in command
    raise Exception('Server response timed out')
Exception: Server response timed out
[07.07.2017 21:11:18] ERROR    Server response timed out
Traceback (most recent call last):
  File "spunky.py", line 594, in taskmanager
    self.check_player_ping()
  File "spunky.py", line 605, in check_player_ping
    self.game.quake.rcon_update()
  File "/home/urt/spunkybot-1.9.0/lib/pyquake3.py", line 188, in rcon_update
    data = self.rcon('status')[1]
  File "/home/urt/spunkybot-1.9.0/lib/pyquake3.py", line 126, in rcon
    r_cmd = self.command('rcon "%s" %s' % (self.rcon_password, cmd))
  File "/home/urt/spunkybot-1.9.0/lib/pyquake3.py", line 120, in command
    raise Exception('Server response timed out')
Exception: Server response timed out
[07.07.2017 21:11:18] ERROR    Server response timed out
Traceback (most recent call last):
  File "spunky.py", line 3419, in rcon_process
    self.quake.rcon_update()
  File "/home/urt/spunkybot-1.9.0/lib/pyquake3.py", line 188, in rcon_update
    data = self.rcon('status')[1]
  File "/home/urt/spunkybot-1.9.0/lib/pyquake3.py", line 126, in rcon
    r_cmd = self.command('rcon "%s" %s' % (self.rcon_password, cmd))
  File "/home/urt/spunkybot-1.9.0/lib/pyquake3.py", line 120, in command
    raise Exception('Server response timed out')
Exception: Server response timed out

```

**Comment by alexanderkress** [comment]
"Server response timed out" means, that the bot was not able to communicate via RCON with the game engine.
Are commands in the game running? I guess any kind of command should not work, since the exception occurs for 'rcon "%s" %s"'.

**Comment by alexanderkress** [comment]
Can you confirm, that the problem occurs for all rotation messages?
According to the log, RCON connection was just for one command on the entire day a problem. With your config, at least 2880 connections will be established per day, and only 1 issue occurred...

**Comment by carca55gr1nd3r** [comment]
I have used not all cmd but the cmd I used worked proper. Just remember some I have tried: !version, !nextmap, !restart, !lookup.
And the bot announced also the welcome msg after connection to the server.

just the rotation messages from rule.conf was missed same time at the server, far beoynd the configured timer of 30 sec.

**Comment by alexanderkress** [comment]
Ok, so the bot is still running fine.
Looks like an invalid config in settings.conf.

Please check the file "devel.log" in /home/urt/spunkybot-1.9.0 check at the end of the file if for the last start the line "Load rotating messages: OK" is shown.
Additionally I would a screenshot of the settings.conf or the file itself, but dont forget to replace your rconpassword before providing this file !!!!
I just need the part below "[rules]"
All other config options are not required.

On my server I am running rules_frequency = 150 without any problem.

**Comment by carca55gr1nd3r** [comment]
Okay so here we are:

last lines of the devel.log:
`    r_cmd = self.command('rcon "%s" %s' % (self.rcon_password, cmd))                                                                                          
  File "/home/urt/spunkybot-1.9.0/lib/pyquake3.py", line 120, in command                                                                                      
    raise Exception('Server response timed out')                                                                                                              
Exception: Server response timed out                                                                                                                          
[25.07.2017 18:33:17] ERROR    Server response timed out                                                                                                      
Traceback (most recent call last):                                                                                                                            
  File "spunky.py", line 3419, in rcon_process                                                                                                                
    self.quake.rcon_update()                                                                                                                                  
  File "/home/urt/spunkybot-1.9.0/lib/pyquake3.py", line 188, in rcon_update                                                                                  
    data = self.rcon('status')[1]                                                                                                                             
  File "/home/urt/spunkybot-1.9.0/lib/pyquake3.py", line 126, in rcon                                                                                         
    r_cmd = self.command('rcon "%s" %s' % (self.rcon_password, cmd))                                                                                          
  File "/home/urt/spunkybot-1.9.0/lib/pyquake3.py", line 120, in command                                                                                      
    raise Exception('Server response timed out')                                                                                                              
Exception: Server response timed out                                                                                                                          
[25.07.2017 23:42:06] ERROR    Server response timed out                                                                                                      
Traceback (most recent call last):                                                                                                                            
  File "spunky.py", line 594, in taskmanager                                                                                                                  
    self.check_player_ping()                                                                                                                                  
  File "spunky.py", line 605, in check_player_ping                                                                                                            
    self.game.quake.rcon_update()                                                                                                                             
  File "/home/urt/spunkybot-1.9.0/lib/pyquake3.py", line 188, in rcon_update                                                                                  
    data = self.rcon('status')[1]                                                                                                                             
  File "/home/urt/spunkybot-1.9.0/lib/pyquake3.py", line 126, in rcon                                                                                         
    r_cmd = self.command('rcon "%s" %s' % (self.rcon_password, cmd))                                                                                          
  File "/home/urt/spunkybot-1.9.0/lib/pyquake3.py", line 120, in command                                                                                      
    raise Exception('Server response timed out')                                                                                                              
Exception: Server response timed out                                                                                                                          
[27.07.2017 17:32:29] ERROR    Server response timed out                                                                                                      
Traceback (most recent call last):                                                                                                                            
  File "spunky.py", line 594, in taskmanager                                                                                                                  
    self.check_player_ping()                                                                                                                                  
  File "spunky.py", line 605, in check_player_ping                                                                                                            
    self.game.quake.rcon_update()                                                                                                                             
  File "/home/urt/spunkybot-1.9.0/lib/pyquake3.py", line 188, in rcon_update                                                                                  
    data = self.rcon('status')[1]                                                                                                                             
  File "/home/urt/spunkybot-1.9.0/lib/pyquake3.py", line 126, in rcon                                                                                         
    r_cmd = self.command('rcon "%s" %s' % (self.rcon_password, cmd))                                                                                          
  File "/home/urt/spunkybot-1.9.0/lib/pyquake3.py", line 120, in command                                                                                      
    raise Exception('Server response timed out')                                                                                                              
Exception: Server response timed out  `


and here the part of settings.conf

`[rules]                                                                                                                                                       
show_rules = 1                                      ; Enable (1) or disable (0) displaying rules / rotation messages                                          
rules_frequency = 30                                ; Interval in seconds between each rule / rotation message default:90                                     
display = chat                                      ; Display rules as 'chat', 'bigtext' or 'server' message. Options: chat/bigtext/server. Default: chat     
                                                                                                                                                              
[bot]                                                                                                                                                         
task_frequency = 60                                 ; Interval in seconds for checking ping, warnings + spectators. Set to 0 to disable this feature. Default:
 60                                                                                                                                                           
max_ping = 200                                      ; Maximum allowed ping, player with higher ping will be kicked. Set to 0 to disable this feature. Default:
 200                                                                                                                                                          
kick_spec_full_server = 10                          ; Warn / kick spectator when more than X players are connected. Set to 0 to disable this feature. Default:
 10                                                                                                                                                           
teamkill_autokick = 1                               ; Enable (1) or disable (0) autokick for team killing. Regulars or higher levels will not get kicked. Defa
ult: 1                                                                                                                                                        
noob_autokick = 0                                   ; Enable (1) or disable (0) autokick of players with low score. Regulars or higher levels will not get kic
ked. Default: 0                                                                                                                                               
spawnkill_autokick = 0                              ; Enable (1) or disable (0) autokick for spawn killing. Admins or higher levels will not get kicked. Defau
lt: 0                                                                                                                                                         
show_country_on_connect = 1                         ; Enable (1) or disable (0) displaying message "Player connected from...". Default: 1                     
show_first_kill = 1                                 ; Enable (1) or disable (0) displaying message "firstblood" / "first nade kill". Default: 1               
show_hit_stats_respawn = 1                          ; Enable (1) or disable (0) displaying hit statistics during respawn. Default: 1                          
autobalancer = 0                                    ; Enable (1) or disable (0) autobalancing of teams at the end of the round/match. Default: 0              
allow_teams_round_end = 1                           ; Enable (1) or disable (0) allowing command !teams only at end of the round/match. Default: 0            
limit_nextmap_votes = 0                             ; Enable (1) or disable (0) limiting successful nextmap votes. Default: 0                                 
kill_survived_opponents = 0                         ; Enable (1) or disable (0) killing of survived opponents when bomb has been exploded/defused. Default: 0 
spam_bomb_planted = 1                               ; Enable (1) or disable (0) spamming the message "Bomb has been planted" in global chat. Default: 0       
spam_knife_kills = 1                                ; Enable (1) or disable (0) displaying player's knife kill series as bigtext. Default: 0                  
spam_nade_kills = 1                                 ; Enable (1) or disable (0) displaying player's HE grenade kill series as bigtext. Default: 0             
spam_headshot_hits = 1                              ; Enable (1) or disable (0) displaying player's headshot hit series as bigtext. Default: 0                
heartbeat = 1                                       ; Enable (1) or disable (0) sending heartbeat signal to our Master Server. Default: 1                     
verbose = 1                                         ; Enable (1) or disable (0) debug messages. Default: 0                                                    
                                                                                                                                                              
[mapcycle]                                                                                                                                                    
dynamic_mapcycle = 1                                ; Enable (1) or disable (0) dynamic mapcycle. If enabled, the rotation of small or big_cycle will be used.
`

I am not sure if that belongs together I noted on my server log following msg spams:

"Info string length exceeded"

Also a msg comes up by try to connect: Couldn't find weapon 106
just restart has fix it... but spunkybot issue stays.

now the issue is up. you can see by connect to : 134.255.231.30:27960

Cheers

**Comment by alexanderkress** [comment]
There is hopefully not that sign **`[rules]** in front of [rules} or ??

Please send me following Linux shell outputs:

```
$ ls -ahl /home/urt/spunkybot-1.9.0

$ ls -ahl /home/urt/spunkybot-1.9.0/conf

$ cat /home/urt/spunkybot-1.9.0/conf/rules.conf
```

**Comment by carca55gr1nd3r** [comment]
There is hopefully not that character `[rules] in front of [rules] or ??

<Carca55>: No want to have it as "insert code" that the tag here at github, for any reason it do not work at here. 

------

Outputs:

![bildschirmfoto vom 2017-07-28 22-32-30](https://user-images.githubusercontent.com/9293934/28735270-c35b9a6e-73e4-11e7-82ae-64a8b2edc462.png)

------

The "Info string length exceeded" message is a problem in your UrbanTerror server config and has nothing to do with Spunky Bot.

<Carca55>: I know, just wana give all possible info, maybe it was linked together.

**Comment by alexanderkress** [comment]
Hmm... I am not able to see any problem, looks all fine....
I will provide a debug-version for you which you can run to see where the problem is located...
